# https://esphome.io/components/sensor/bme680
---
substitutions:
  bme680_prefix: ''

# To modify address or change default settings or remove a sensor,
# you can add the following in your config that includes this package:
# sensor:
#   - platform: bme680
#     id: !extend bme680_sensor
#     address: 0x76
#     pressure: !remove
sensor:
  - platform: bme680
    id: bme680_sensor
    address: 0x77
    update_interval: 60s
    temperature:
      id: bme680_temperature
      name: ${bme680_prefix}Temperature
    pressure:
      id: bme680_pressure
      name: ${bme680_prefix}Pressure
      device_class: atmospheric_pressure
    humidity:
      id: bme680_humidity
      name: ${bme680_prefix}Humidity
    gas_resistance:
      id: bme680_gas_resistance
      name: ${bme680_prefix}Gas Resistance
  - platform: template
    id: bme680_iaq
    name: ${bme680_prefix}Indoor Air Quality
    unit_of_measurement: IAQ
    icon: mdi:gauge
    lambda: !lambda |-
      return log(id(bme680_gas_resistance).state) + 0.04 * id(bme680_humidity).state;
    accuracy_decimals: 0
    state_class: measurement

text_sensor:
  - platform: template
    id: bme680_iaq_classification
    name: ${bme680_prefix}IAQ Classification
    icon: mdi:checkbox-marked-circle-outline
    lambda: !lambda |-
      if (int(id(bme680_iaq).state) <= 50) {
        return {"Excellent"};
      } else if (int(id(bme680_iaq).state) <= 100) {
        return {"Good"};
      } else if (int(id(bme680_iaq).state) <= 150) {
        return {"Lightly polluted"};
      } else if (int(id(bme680_iaq).state) <= 200) {
        return {"Moderately polluted"};
      } else if (int(id(bme680_iaq).state) <= 250) {
        return {"Heavily polluted"};
      } else if (int(id(bme680_iaq).state) <= 350) {
        return {"Severely polluted"};
      } else if (int(id(bme680_iaq).state) <= 500) {
        return {"Extremely polluted"};
      } else {
        return {"unknown"};
      }
