# https://esphome.io/components/sensor/scd4x
---
substitutions:
  scd4x_prefix: ''

api:
  actions:
    - action: calibrate_co2_value
      variables:
        co2_ppm: int
      then:
        - scd4x.perform_forced_calibration:
            value: !lambda |-
              return co2_ppm;
            id: scd4x_sensor

# To modify default settings, you can add the following in your config that includes this package:
# sensor:
#   - platform: scd4x
#     id: !extend scd4x_sensor
#     ambient_pressure_compensation_source: bme680_pressure
#     temperature: !remove
#     humidity: !remove
sensor:
  - platform: scd4x
    id: scd4x_sensor
    co2:
      name: ${scd4x_prefix}CO2
      id: scd4x_co2
    temperature:
      name: ${scd4x_prefix}Temperature
      id: scd4x_temperature
    humidity:
      name: ${scd4x_prefix}Humidity
      id: scd4x_humidity
    update_interval: 10s  # Defaults to 60s
    automatic_self_calibration: false  # Defaults to true
    # Default values
    # temperature_offset: 4°C
    # measurement_mode: periodic
    # address: 0x62

button:
  - platform: template
    name: Calibrate CO2
    id: calibrate_scd4x
    entity_category: config
    on_press:
      then:
        - scd4x.perform_forced_calibration:
            value: 419  # outside average April 2022
            id: scd4x_sensor
  - platform: template
    name: Factory Reset CO2
    id: factory_reset_scd4x
    entity_category: config
    on_press:
      then:
        - scd4x.factory_reset: scd4x_sensor
