# https://esphome.io/components/sensor/scd4x
---
substitutions:
  scd4x_prefix: ''

api:
  actions:
    - action: calibrate_co2_value
      variables:
        co2_ppm: int
      then:
        - scd4x.perform_forced_calibration:
            value: !lambda |-
              return co2_ppm;
            id: scd4x_sensor

# To modify default settings, you can add the following in your config that includes this package:
# sensor:
#   - platform: scd4x
#     id: !extend scd4x_sensor
#     ambient_pressure_compensation_source: bme680_pressure
#     temperature: !remove
#     humidity: !remove
sensor:
  - platform: scd4x
    id: scd4x_sensor
    co2:
      name: ${scd4x_prefix}CO2
      id: scd4x_co2
      on_raw_value:
        then:
          - sensor.template.publish:
              id: scd4x_co2_raw
              state: !lambda 'return x;'
      filters:
        - median:
            window_size: 5
            send_every: 1
        - sliding_window_moving_average:
            window_size: 4
            send_every: 2 # Report every 60s (2 * 30s interval)
        - delta: 1
    temperature:
      name: ${scd4x_prefix}Temperature
      id: scd4x_temperature
      accuracy_decimals: 1
      filters:
        - sliding_window_moving_average:
            window_size: 4
            send_every: 2
        - delta: 0.1
    humidity:
      name: ${scd4x_prefix}Humidity
      id: scd4x_humidity
      accuracy_decimals: 0
      filters:
        - sliding_window_moving_average:
            window_size: 4
            send_every: 2
        - delta: 1
    # Use low_power_periodic for a good balance of responsiveness and low self-heating.
    measurement_mode: low_power_periodic
    # Match the update_interval to the measurement interval.
    update_interval: 30s
    # Keep ASC enabled for typical indoor environments with regular ventilation.
    automatic_self_calibration: true
    # Default values
    # temperature_offset: 4°C
    # address: 0x62

  - platform: template
    id: scd4x_co2_raw
    internal: true

button:
  - platform: template
    name: Calibrate CO2
    id: calibrate_scd4x
    entity_category: config
    on_press:
      then:
        - scd4x.perform_forced_calibration:
            # Global Monthly Mean CO2
            # https://gml.noaa.gov/ccgg/trends/global.html
            value: 426
            id: scd4x_sensor
  - platform: template
    name: Factory Reset CO2
    id: factory_reset_scd4x
    disabled_by_default: true
    entity_category: config
    on_press:
      then:
        - scd4x.factory_reset: scd4x_sensor
